### ISSUE TITLE
"Back" does not work on "Virtual Machine Storage" screen, when host has a single disk

### ISSUE THREAD

**Issue by ydirson** [xenserver/host-installer#7]
When host has a single disk, the "Select Primary Disk" screen is skipped.  In this case, hitting "Back" from "Virtual Machine Storage" screen gets back to "Select Primary Disk" which is not shown, and the user is just presented "Virtual Machine Storage" again: "Back" simply does not work.

Changing the "Select Primary Disk" to be displayed even with a single disk would not only solve this issue, but would also let the user have a better understanding of what happens, as
- that screen is the one saying "disks with insufficient space are not shown"
- some users reportedly confuse the "Virtual Machine Storage" screen with primary disk selection when there is no screen shown for the latter

**Comment by rosslagerwall** [comment]
Yes, that sounds like a good idea to me.
